# Generated by Django 5.2.12 on 2026-03-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_max_count_vm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_count_vm',
        ),
    ]
