# Generated by Django 5.2.12 on 2026-03-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
                ('total_cpu_cores', models.PositiveIntegerField(default=16)),
                ('total_ram_mb', models.PositiveIntegerField(default=32768)),
                ('total_disk_gb', models.PositiveIntegerField(default=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System resource',
                'verbose_name_plural': 'System resources',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cpu_cores_limit', models.PositiveIntegerField()),
                ('ram_mb_limit', models.PositiveIntegerField()),
                ('disk_gb_limit', models.PositiveIntegerField()),
                ('network_mbps_limit', models.PositiveIntegerField()),
                ('max_vms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TenantAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='vm_manager.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='members',
            field=models.ManyToManyField(related_name='tenants', through='vm_manager.TenantAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_key', models.CharField(max_length=50)),
                ('docker_image', models.CharField(max_length=255)),
                ('container_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('starting', 'Запускается'), ('running', 'Работает'), ('stopping', 'Останавливается'), ('stopped', 'Остановлен'), ('restarting', 'Перезагружается'), ('failed', 'Ошибка')], default='starting', max_length=20)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('ram_mb', models.PositiveIntegerField()),
                ('disk_gb', models.PositiveIntegerField()),
                ('network_mbps', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='vm_manager.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeakResourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('vm', 'Virtual machine'), ('tenant', 'Tenant')], max_length=16)),
                ('cpu_cores_delta', models.IntegerField(default=0)),
                ('ram_mb_delta', models.IntegerField(default=0)),
                ('disk_gb_delta', models.IntegerField(default=0)),
                ('network_mbps_delta', models.IntegerField(default=0)),
                ('max_vms_delta', models.IntegerField(default=0)),
                ('apply_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_peak_schedules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peak_schedules', to='vm_manager.tenant')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peak_schedules', to='vm_manager.virtualmachine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VMActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='vm_manager.virtualmachine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VMMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('docker', 'Docker'), ('simulated', 'Simulated')], default='docker', max_length=16)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_mb', models.FloatField(default=0.0)),
                ('net_rx_mb', models.FloatField(default=0.0)),
                ('net_tx_mb', models.FloatField(default=0.0)),
                ('block_read_mb', models.FloatField(default=0.0)),
                ('block_write_mb', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics_snapshots', to='vm_manager.tenant')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics_snapshots', to='vm_manager.virtualmachine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vm', 'created_at'], name='vm_manager__vm_id_6314ed_idx'), models.Index(fields=['tenant', 'created_at'], name='vm_manager__tenant__1042ae_idx')],
            },
        ),
    ]
