# Generated by Django 5.2.12 on 2026-03-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='image_key',
        ),
    ]
